apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-server-ingress
  namespace: argo-rollouts
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #kubernetes.io/tls-acme: "true"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - path: /rollouts
        pathType: Prefix
        backend:
          service: 
            name: argo-rollouts-dashboard
            port:
              number: 3100